### PR TITLE
Optimize search and memory usage for AVR

### PR DESCRIPTION
**Pull request by JoakimSoderberg**
- Separate table into two (to enable using generic algorithms on both).
- On AVR support saving the tables into flash instead of RAM. 520 bytes of ram usage in old version.
- Made the tables "unsigned int" instead of "unsigned long" since it was not needed. Instead we scale the temperatures at use.
- Added a binary search instead of linear search over the value giving O(log(n)) instead of O(n).
- Added defines to turn on all of these new things conditionally when compiling (Default is to work as previous version with linear search).
- Made a nicer test harness to make it easier to validate against the test_\* files

### CODE REVIEW

**Comment by JoakimSoderberg** [comment]
Had to optimise on size to fit this in my arduino project. I added the binary search just for the sake of it, felt unnecessary to do a linear search :)

Maybe you could help with this?

I'm using this chip, it has a built-in temperatur sensor that I'm using for the cold junction temperature:
https://datasheets.maximintegrated.com/en/ds/DS2762.pdf

Using this lib to communicate with it https://github.com/nigelb/Arduino-DS2762

I am not an electronics wiz so I bought it in a ready package together with a K-type thermocouple connector:
image
from here:
https://www.m.nu/termoelementinterface-hoga-temperaturer-version-p-457.html

All it says is that OWFS supports it:
http://owfs.org/index.php?page=thermocouples
From this image as I understand it, I want to get the voltage difference between `Vss` and `SNS`:
image

The DS2762 lib I'm using has a function `ReadADC()` that reads this (from datasheet):

> VOLTAGE MEASUREMENT
> The DS2762 continually measures the voltage between pins VIN and VSS over a 0 to 4.75V range. The voltage
> register is updated in two’s-complement format every 3.4ms with a 4.88mV resolution. Voltages above the
> maximum register value are reported as the maximum value. Figure 7 shows the voltage register format. 

And for me, that value never changes, it just stays at **208** no matter if the thermocouple is connected or not. Compare that to the internal temperature sensor that changes right away if I touch the chip with my finger to transfer some heat.

Also when I look at the chipset it looks as if one of the thermocouple wires are connected to all 3 SNS-pins on the chip:
screenshot 2016-01-10 01 05 36

Do you got any clues on what to read from exactly? :/

**Comment by JoakimSoderberg** [comment]
Ok I solved it, it turned out I was supposed to read the "current measurement register", which might be a bit unintuitive since it's supposed to be a voltage, but there is a secondary mode:

> For the external sense resistor configuration, the DS2762 writes the measured VIS voltage to the current register, with a 15.625microV resolution and a full-scale 64mV range.

**Comment by JoakimSoderberg** [comment]
@Miceuz bump

**Comment by Miceuz** [comment]
Hi, thanks again for the pull request. I have had a binary search implemented at first, but decided to remove it later to have less interface and options, etc. Now when the data is in permgen it especially makes sense.

Regarding your question - I have never worked with DS2760, but this thermocouple application is more of a hack than a proper thing. It's a battery monitoring chip by design. Internally it has a small resistor to measure the current from the battery, but when you hook up a thermocouple as shown, it happens that thermocouple voltage is developed across internal current shunt resistor and can be measured by precision microvolt level circuitry inside the chip - that explains why you have to read it from the current register.

**Comment by JoakimSoderberg** [comment]
Ok thanks for merging and for the explanation :)

**Pull request merged**
